# Generated by Django 3.2.25 on 2024-07-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_merge_20240318_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_conflict',
            field=models.BooleanField(default=False, help_text='True if the task has conflicting annotations', verbose_name='has conflict'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['has_conflict'], name='task_has_con_0e0a30_idx'),
        ),
    ]
