# Generated by Django 3.2.25 on 2024-09-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_failedprediction'),
        ('tasks', '0049_auto_20240814_1048'),
    ]

    operations = [
    ]
